// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utpvznducomormcujrug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cHZ6bmR1Y29tb3JtY3VqcnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mjc5MDIsImV4cCI6MjA1ODIwMzkwMn0.TU55tRwplVTr25XH9dwfg6p6P_nXB5bGHJ9scxfgzWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);